### ISSUE TITLE
==> Possibly missing firmware

### ISSUE THREAD

**Issue by iconized** [Snigdha-OS/snigdhaos-arctic#1]
**BUG**
==> WARNING: Possibly missing firmware for module: 'aic94xx'
==> WARNING: Possibly missing firmware for module: 'bfa'
==> WARNING: Possibly missing firmware for module: 'qed'
==> WARNING: Possibly missing firmware for module: 'qla1280'
==> WARNING: Possibly missing firmware for module: 'qla2xxx'
==> WARNING: Possibly missing firmware for module: 'wd719x'
@eshanized Fixing?

**Comment by eshanized** [comment]
@iconized you need a package called [mkinitcpio-firmware](https://aur.archlinux.org/pkgbase/mkinitcpio-firmware) for this. If you have `yay` or `paru` installed then you can use:

```bash
yay -S mkinitcpio-firmware
```
*NOTE: We will update `snigdhaos-core` repository in 30 mins. you can install it via pacman.*
```bash
sps mkinitcpio-firmware
```
or

```bash
sudo pacman -S mkinitcpio-firmware
```

I hope it will help you . If you have further issues, let me know.
